language: php

matrix:
    include:
        - php: 7.0
        - php: 7.1
        - php: 7.2

install:
    - composer self-update
    - composer install --prefer-source
    - composer require php-coveralls/php-coveralls

script:
    - vendor/bin/phpunit --colors=always --coverage-clover clover.xml
    - vendor/bin/phpcs

after_script:
    - vendor/bin/php-coveralls -v
